### ISSUE TITLE
Question generateBaseImage()

### ISSUE THREAD

**Issue by Zenos-Paradox** [rmislam/PythonSIFT#24]
Hi!

What's the `assumed_blur` parameter for? what does it mean?
I hope someone is still reading theese...
EDIT: Also, what's the point of upsampling the image? isn't it the same as just bluring it but ending up with more pixels to go through?

**Comment by rmislam** [comment]
Hey @Zenos-Paradox , thanks for your interest in this repo!
The answers to both of your questions can be found in the second paragraph of section 3.3 in the original SIFT paper (https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf).

The `assumed_blur` parameter is there to prevent aliasing. More intuitively, you can think of this parameter as the blur of an average camera. SIFT is meant to be used on real images, and all real cameras have some amount of blur. `0.5` is a typical value, and the original SIFT algorithm uses this value.

As for upsampling: since we are performing lots of smoothing on the original image, we're throwing away high-frequency spatial information. By upsampling, we can preserve some of this info. As mentioned in the paper, this results in almost 4 times as many keypoints, and upsampling by more than 2 doesn't seem to add significantly more keypoints.

**Comment by rmislam** [comment]
@Zenos-Paradox 
Haven't heard from you, but I believe I've answered your question, so I'm closing this issue. Feel free to open it again if you disagree.
