### ISSUE TITLE
Two questions about keypoint scale

### ISSUE THREAD

**Issue by CrazyDoom** [rmislam/PythonSIFT#6]
HI, thank you for the great work, it helps me a lot when learning SIFT, I have to 2 questions about keypoint.size

1. When computing keypoint.size in localizeExtremumViaQuadraticFit(), you used octave_index + 1 instead of octave_index, is this because the origin input image is doubled by linear interpolation?

2. In computeKeypointsWithOrientations, the scale is muliplied by 0.5 and divided by 2 ** octave_index, it's a little different from the origin paper, am I missing something？

**Comment by CrazyDoom** [comment]
> HI, thank you for the great work, it helps me a lot when learning SIFT, I have to 2 questions about keypoint.size
> 
>     1. When computing keypoint.size in localizeExtremumViaQuadraticFit(), you used octave_index + 1 instead of octave_index, is this because the origin input image is doubled by linear interpolation?
> 
>     2. In computeKeypointsWithOrientations, the scale is muliplied by 0.5 and divided by 2 ** octave_index, it's a little different from the origin paper, am I missing something？

I think the scale to compute the orientation should be `2 ** ((image_index + extremum_update[2]) / float32(num_intervals))) * (2 ** (octave_index ))`
it's different from the scale in computeKeypointsWithOrientations()

**Comment by rmislam** [comment]
Hi there, sorry for the slow response. Thanks a lot for investigating the code in this repo so closely.

The way `keypoint.size` is computed in `localizeExtremumViaQuadraticFit()` is actually consistent with the way it's used in `computedKeypointsWithOrientations()`. Let me explain.

The way I compute `keypoint.size` is a direct translation of the way it's done in OpenCV:
https://github.com/opencv/opencv_contrib/blob/master/modules/xfeatures2d/src/sift.cpp

Take a look at line 572 here, which corresponds to line 181 in `pysift.py`:

`kpt.size = sigma*powf(2.f, (layer + xi) / nOctaveLayers)*(1 << octv)*2;`  (OpenCV sift.cpp)

`keypoint.size = sigma * (2 ** ((image_index + extremum_update[2]) / float32(num_intervals))) * (2 ** (octave_index + 1))`  (PythonSIFT pysift.py)

Note the last part in `sift.cpp`:  `(1 << octv)*2`. This is mathematically equivalent to `2 ** (octave_index + 1)`.

Now take a look at line 661 in `sift.cpp`, which corresponds to line 227 in `pysift.py`:

`float scl_octv = kpt.size*0.5f/(1 << o);`  (OpenCV sift.cpp)

`scale = scale_factor * 0.5 * keypoint.size / float32(2 ** octave_index)`  (PythonSIFT pysift.py)

Again, this is just a direct translation. I'm recovering `sigma * (2 ** ((image_index + extremum_update[2]) / float32(num_intervals)))`. The `* 0.5 / float32(2 ** octave_index)` operation reverses the `* (2 ** (octave_index + 1))` operation done before.

I see now that these two lines don't have consistent syntax. I'll change line 181 to this:
``keypoint.size = sigma * (2 ** ((image_index + extremum_update[2]) / float32(num_intervals))) * 2 * (2 ** octave_index)``

and line 227 to this:
`scale = scale_factor * keypoint.size / float32(2 * (2 ** octave_index))`

This will make it clearer how these two lines are related. There's no change mathematically -- I've just rearranged the expressions. I'll also add comments.

**Now you're wondering why there's an extra `* 2` when computing the size**. To be honest, I'm not sure myself why OpenCV creates the size this way. When I was writing PythonSIFT, my first instinct was to not include this `* 2`. However, I wanted the sizes to be consistent with the way OpenCV does them so that you can directly compare PythonSIFT keypoints and OpenCV keypoints at every step of SIFT computation.

I don't think it has anything to do with the double-size base image, because later on we are multiplying `keypoint.size` by 0.5 in `convertKeypointsToInputImageSize()`.

I don't believe this is a bug in OpenCV, because it's used very consistently throughout their code. For example, see lines 1065 and 1072 in `sift.cpp`. Since they keep going back and forth between multiplying by 2 and multiplying by 0.5, and they do so consistently, at the moment I don't see why they need this `* 2` in the first place. I included it in PythonSIFT just to be consistent with OpenCV. However, I may consider removing it to make the code easier to understand. Please allow me to think about this for a bit.

Thanks for pointing this out! Does this answer your questions?

**Comment by rmislam** [comment]
Hi there! Thanks for looking into PythonSIFT so deeply.

1. 
Yes, I'm using `octave_index + 1` instead of `octave_index` because we double the input image size. Later in `convertKeypointsToInputImageSize()`, we do `keypoint.size *= 0.5` to account for this.

2.
Actually, the way `scale` is computed in `computeKeypointsWithOrientations()` is consistent with the way `keypoints.size` is computed in `localizeExtremumViaQuadraticFit()`. Let's compare line 181:

`keypoint.size = sigma * (2 ** ((image_index + extremum_update[2]) / float32(num_intervals))) * (2 ** (octave_index + 1))`

with line 227:

`scale = scale_factor * 0.5 * keypoint.size / float32(2 ** octave_index)`

Note that we can rewrite line 227 like this, and it's mathematically equivalent:

`scale = scale_factor * keypoint.size / float32(2 ** (octave_index + 1))`.

In fact, I made this change in the latest commit in order to be consistent with line 181. Sorry for the confusion. However, there's nothing wrong with the original line 227. We are simply reversing the `* (2 ** (octave_index + 1))`operation done in line 118 to recover the scale. We then multiply by `scale_factor`, as mentioned in the paper.

Note that `size` here corresponds to the same `size` variable used in OpenCV's SIFT implementation, which you can find here:

https://github.com/opencv/opencv_contrib/blob/master/modules/xfeatures2d/src/sift.cpp

If you take a look at lines 572 and 661, you can see they compute size and scale the same way. You can even set up breakpoints in OpenCV's `sift.cpp` and PythonSIFT's `pysift.py`, and compare the keypoints at each step of the computation and verify they are the same within rounding error. The `size` variable isn't mentioned in the original SIFT paper -- it's just a convenient way to store the `scale` across different octaves and layers using a single number.

I hope this helps! Does this answer your questions?

**Comment by rmislam** [comment]
I believe this issue has been resolved, so I'm going to close it. Please feel free to reopen this issue if you feel your question hasn't been answered.
