### ISSUE TITLE
Could I give you question? (num_intervals)

### ISSUE THREAD

**Issue by sunshower76** [rmislam/PythonSIFT#9]
in this paper 'Distinctive Image Features from Scale-Invariant Keypoints' which link is "https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf", **num_intervals=2** but you implemented  **num_intervals=3**. 

Do you have reason set '3' for the default value of 'num_intervals'?

**Comment by rmislam** [comment]
Hello, thanks for your question!

Yes, I'm using the OpenCV default of `num_intervals = 3`. You can take a look at line 125 here:

https://github.com/opencv/opencv_contrib/blob/master/modules/xfeatures2d/src/sift.cpp

All the parameters in PythonSIFT have the same defaults as OpenCV, since PythonSIFT is meant to be compared with OpenCV and to serve as its drop-in replacement. There are some implementation details beyond what is covered in the original paper, and I definitely recommend looking at the OpenCV code as a supplement.

I hope this answers your question!

**Comment by rmislam** [comment]
I believe this issue has been resolved, so I'm going to close it. Please feel free to reopen this issue if you feel your question hasn't been answered.
